[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[override]]
  name = "github.com/gin-gonic/gin"
  revision = "1.3.3"
  source = "https://github.com/ysitd-cloud/gin"

[[constraint]]
  branch = "master"
  name = "code.ysitd.cloud/gin/utils"

[[constraint]]
  branch = "master"
  name = "github.com/tonyhhyip/go-di-container"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/secure"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.11.3"

[[constraint]]
  branch = "master"
  name = "code.ysitd.cloud/grpc/schema"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  revision = "967789050ba94deca04a5e84cce8ad472ce313c1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "golang.ysitd.cloud/db"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  name = "golang.ysitd.cloud/gin/sessions"
  version = "4.0.0"

[[constraint]]
  name = "github.com/tonyhhyip/vodka"
  version = "2.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/inject"

[[constraint]]
  name = "golang.ysitd.cloud/log"
  version = "1.0.0"
